Csci42/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', include('login.urls', namespace="login")),
    path('admin/', admin.site.urls),
    path('trees/', include('trees.urls', namespace='trees')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path

from . import views   

urlpatterns = [
    path('', views.login, name='login'),
    path("users/add/", views.add, name="add"),
    path("homepage/", views.homepage, name="homepage"),
]

app_name = "login"

trees/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views   

urlpatterns = [
    path("treeRecords/", views.treeRecords.as_view(), name="treeRecords"),
    path("newTreeRecord/", views.newTreeRecord, name="newTreeRecord"),
    path('generate-qr/<str:data>/', views.generate_qr, name='generate_qr'),
]

app_name = "trees"

login/models.py
from django.db import models
from django.core.validators import MaxValueValidator

DEFAULT_ID_NUM = 1

# Create your models here.
class User(models.Model):
    id_num = models.IntegerField(default=DEFAULT_ID_NUM, validators=[MaxValueValidator(9999999)], primary_key=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    password = models.CharField(max_length=16)
    administrator = models.BooleanField(default=False)

    def __str__(self):
        if (self.administrator):
            return 'Admin: {} {}'.format(self.first_name, self.last_name)

        return 'Student: {} {}'.format(self.first_name, self.last_name)

trees/models.py
from django.db import models

# Create your models here.
class Tree(models.Model):
    section = models.CharField(max_length=100, default="Tree")
    age = models.CharField(max_length=500)
    variety = models.CharField(max_length=500)
    soil_moisture = models.CharField(max_length=500)
    temperature = models.CharField(max_length=500)
    humidity = models.CharField(max_length=500)
    light_exposure = models.CharField(max_length=500)
    nutrient_levels = models.CharField(max_length=500)
    pest_disease_outbreaks = models.CharField(max_length=500)
    harvestTime = models.TimeField(auto_now=False, auto_now_add=False)
    harvestDate = models.DateField(null=True, blank=True)
    tree_image = models.ImageField(upload_to="treeRecords", null=True, blank=True)

    
    def __str__(self):
        return'{}'.format(self.id)

login/forms.py
from django.forms import ModelForm
from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["id_num", "last_name", "first_name", 
            "password", "administrator"]

trees/forms.py
from django.forms import ModelForm, DateInput
from django.forms.widgets import SelectDateWidget
from .models import Tree
from django import forms

class TreeRecordForm(ModelForm):
    harvestDate = forms.DateField(widget=SelectDateWidget)
    harvestTime = forms.TimeField(widget=DateInput(attrs={'type': 'time'}))

    class Meta:
        model = Tree
        fields = ["section", "age", "variety", "soil_moisture", "temperature",
                  "humidity", "light_exposure", "nutrient_levels", "pest_disease_outbreaks",
                  "harvestTime", "harvestDate", "tree_image"]

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .models import User
from .forms import UserForm

# Create your views here.

def add(request): # signup
    if request.method == "POST":
        userForm = UserForm(request.POST, request.FILES)
        if userForm.is_valid():
            new_user = userForm.save()
            return redirect("login:login")
    else:
        userForm = UserForm()
        return render(request, "add.html", 
            {"userForm": userForm})

def login(request): # sign in
    if request.method == "POST":
        id_num = request.POST.get('id_num')
        password = request.POST.get('password')
        try:
            user = User.objects.get(id_num=id_num)
            if password == user.password:
                return redirect("login:homepage")
            return render(request, 'login.html', {'error_message': 'Invalid username or password.'})
        except User.DoesNotExist:
            return render(request, 'login.html', {'error_message': 'Invalid username or password.'})
    else:
        return render(request, 'login.html')

def homepage(request):
    return render(request, "homepage.html")

trees/views.py
from django.shortcuts import render, redirect
from django.template import Template, Context, loader
from .models import Tree
from .forms import TreeRecordForm
from django.template.loader import get_template
from django.views import View
from django.http import HttpResponse
import qrcode

# Create your views here.
class treeRecords(View):
    template = "treeRecords.html"
    def get(self, request):
        all_tree_records = Tree.objects.filter()
        context = {
            "all_tree_records": all_tree_records
        }
        
        return render(request, "trees/treeRecords.html", context)
    
def newTreeRecord(request):
    if request.method == "POST":
        tree_record_form = TreeRecordForm(request.POST, request.FILES)
        if tree_record_form.is_valid():
            tree_record_form.save()
            return redirect("trees:newTreeRecord")
        else:
            tree_record_form = TreeRecordForm()
    return render(request, "trees/add.html", {"tree_record_form": TreeRecordForm})

def generate_qr(request, data):
    # Generate QR code image
    img = qrcode.make(data)

    # Return image as HTTP response
    response = HttpResponse(content_type='image/png')
    img.save(response, 'PNG')
    return response

login/templates/add.html
{% extends 'base.html' %}

{% block title %}Add User{% endblock %}

{% block content %}
<h1>Add User</h1>
<form method="POST" action="{% url 'login:add' %}" 
    enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in userForm %}
    <div class="form-field">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
{% endfor %}

    <button class="button" type="submit">Save New User</button>
    <button onclick="window.location.href='../..';">Back to Login Page</button>
</form>
{% endblock %}

login/templates/homepage.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
<h1>Welcome to the Cacao App homepage</h1>
<button onclick="window.location.href='../../trees/treeRecords/';">View Tree Records</button>

<input placeholder="Tree ID Number" type="number" name="id_num" class="string" required>
<button onclick="window.location.href='../../trees/generate-qr/EnterTreeNumberHere';">Generate a QR Code</button>
{% endblock %}

login/templates/login.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
  <h1>Welcome to Cacao App</h1>

  <h2>Login</h2>
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_num">ID Number:</label>
      <input placeholder="Enter 6-digit ID number" type="number" name="id_num" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input placeholder="Enter password" type="password" name="password" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    <span>{{error_message}}</span>
  </form>


<button onclick="window.location.href='users/add/';">Sign up here</button>
{% endblock %}

trees/templates/trees/add.html
{% extends 'base.html' %}
{% block head %}
  {% comment %} {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}"> {% endcomment %}
{% endblock %}

{% block content %}
  <h1> New Tree </h1>
  <form action="{% url 'trees:newTreeRecord' %}" method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{tree_record_form.as_p}}
    <button class="button" type="submit">Submit Tree Record</button>
  </form>
  <a href="/trees/treeRecords/"> <button>Back to Tree Records</button> </a>
{% endblock %}

trees/templates/trees/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale-1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}Woah, a page{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>

trees/templates/trees/qrCodeGenerator.html
{% extends "base.html" %}

{% block content %}
  <h1>Generate QR Code</h1>
  <img src="{% url 'generate_qr' data='Hello, World!' %}">
{% endblock %}

trees/templates/trees/treeRecords.html
{% extends "base.html" %}

{% block content %}
  <center><h1>Inventory of Cacao Trees</h1></center>
  {% for tree in all_tree_records %}
    <li><b>Location: </b>{{tree.section}}</li>
    <li><b>Age: </b>{{tree.age}}</li>
    <li><b>Variety: </b>{{tree.variety}}</li>
    <li><b>Soil Moisture: </b>{{tree.soil_moisture}}</li>
    <li><b>Temperature: </b>{{tree.temperature}}</li>
    <li><b>Humidity: </b>{{tree.humidity}}</li>
    <li><b>Light Exposure: </b>{{tree.light_exposure}}</li>
    <li><b>Nutrient Levels: </b>{{tree.nutrient_levels}}</li>
    <li><b>Pest Disease Outbreaks: </b>{{tree.pest_disease_outbreaks}}</li>
    <li><b>Harvest Times: </b>{{tree.harvestTime}}</li>
    {% if tree.tree_image %}
      <li><b>Tree Picture:</b></li>
      <img width="250" height="250" src="{{tree.tree_image.url}}">
    {% endif %}
    <br>
  {% endfor %}
  <a href="/trees/newTreeRecord"> <button>Submit a Tree</button> </a>
  <button onclick="window.location.href='../../login/homepage/';">Back to Homepage</button>
  {% endblock %}